# Check why the cropping does not work for some images.

In [1]:
import matplotlib.pyplot as plt

import sys
sys.path.append("../../nansat/")
from nansat import Nansat

sys.path.append("..")
import sar

In [2]:
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt, make_path_filter

local_api = SentinelAPI(None, None, "https://colhub-archive.met.no" ,timeout=180)
api = SentinelAPI(None, None, "https://scihub.copernicus.eu/dhus", timeout=180)

data_dir = "/lustre/storeB/project/IT/geout/machine-ocean/data_raw/sentinel/"

In [3]:
# import dict containing metadata for in-situ data
# https://raw.githubusercontent.com/jerabaul29/MachineOcean_WP1_WHOI/main/mo_whoi_data/data_files/in_situ_dict.py
# from private repo at https://github.com/jerabaul29/MachineOcean_WP1_WHOI
import time
import os

os.environ["TZ"] = "UTC"
time.tzset()

import datetime
import pytz

utc_timezone = pytz.timezone("UTC")

wd = os.getcwd()

os.chdir("../../MachineOcean_WP1_WHOI/mo_whoi_data/data_files")

import in_situ_dict
in_situ_obs = in_situ_dict.get_in_situ_metadata()

os.chdir(wd)

print(in_situ_obs.keys())

dict_keys(['Endurance_8', 'Irminger_7', 'SPURS2', 'Endurance_4', 'Irminger_6', 'Pioneer_5', 'CLIMODE', 'Endurance_9', 'Pioneer_10', 'SouthernOcean2', 'Endurance_3', 'Pioneer_3', 'SPURS1', 'Endurance_7', 'Irminger_3', 'Pioneer_7', 'Pioneer_6', 'Pioneer_8'])


In [4]:
##### read pickled imported in-situ measurements metadata with attached colocated Sentinel-1 sat products metadata
# (to avoid having to rerun the API search)
import pickle

with open('in_situ_obs.pickle', 'rb') as handle:
    in_situ_obs = pickle.load(handle)

with open('products_scihub.pickle', 'rb') as handle:
    products_scihub = pickle.load(handle)

In [5]:
in_situ_obs.keys()

dict_keys(['Endurance_8', 'Irminger_7', 'SPURS2', 'Endurance_4', 'Irminger_6', 'Pioneer_5', 'CLIMODE', 'Endurance_9', 'Pioneer_10', 'SouthernOcean2', 'Endurance_3', 'Pioneer_3', 'SPURS1', 'Endurance_7', 'Irminger_3', 'Pioneer_7', 'Pioneer_6', 'Pioneer_8'])

# Files that failed

In [6]:
buoy = 'Irminger_7'
fname = 'S1B_EW_GRDM_1SDH_20210728T201123_20210728T201223_027999_03571C_4E75.SAFE'
station_lat = in_situ_obs[buoy]['lat'][0]
station_lon = in_situ_obs[buoy]['lon'][0]

In [7]:
station_lat

59.9337

In [8]:
station_lon

-39.47378

In [9]:
epsilon = 0.00005

In [10]:
s0, s0_norm, inc, az, grid_lons, grid_lats, pol = sar.sar_params(
    data_dir + fname,
    station_lon=station_lon,
    station_lat=station_lat,
    epsilon=epsilon
)

/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':
/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':
/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':
/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':


RuntimeError: Invalid dataset dimensions : 0 x 10003

In [11]:
epsilon = 0.0005

In [12]:
s0, s0_norm, inc, az, grid_lons, grid_lats, pol = sar.sar_params(
    data_dir + fname,
    station_lon=station_lon,
    station_lat=station_lat,
    epsilon=epsilon
)

In [13]:
grid_lons

array([[-39.4751683 , -39.474469  ],
       [-39.47532087, -39.47462156],
       [-39.47547344, -39.47477412]])

# -------------------------------

In [14]:
buoy = 'Irminger_3'
fname = 'S1A_EW_GRDM_1SDH_20161119T202719_20161119T202824_014016_01696B_88AF.SAFE'
station_lat = in_situ_obs[buoy]['lat'][0]
station_lon = in_situ_obs[buoy]['lon'][0]

In [15]:
station_lat

59.9337

In [16]:
station_lon

-39.47378

In [17]:
s0, s0_norm, inc, az, grid_lons, grid_lats, pol = sar.sar_params(
    data_dir + fname,
    station_lon=station_lon,
    station_lat=station_lat,
    epsilon=epsilon
)

/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':
/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':
/home/paulinast/repos/github/nansat/nansat/nansat.py:1125: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if mappername is not '':


ValueError: Cropping region is outside the image! offset: 10411.000000 size: 2.000000

In [18]:
n = Nansat(data_dir + fname)
n.get_corners()

(array([-45.28665831, -47.17225249, -38.63948871, -39.7694533 ]),
 array([56.29524491, 60.09721186, 57.01300696, 60.85116796]))

In [19]:
fname = 'S1B_EW_GRDM_1SDH_20170804T202641_20170804T202745_006795_00BF51_CD72.SAFE'

In [20]:
s0, s0_norm, inc, az, grid_lons, grid_lats, pol = sar.sar_params(
    data_dir + fname,
    station_lon=station_lon,
    station_lat=station_lat,
    epsilon=epsilon
)

ValueError: Cropping region is outside the image! offset: 10401.000000 size: 2.000000

In [21]:
fname = 'S1B_EW_GRDM_1SDH_20170720T084730_20170720T084830_006569_00B8D6_F92F.SAFE'

In [22]:
s0, s0_norm, inc, az, grid_lons, grid_lats, pol = sar.sar_params(
    data_dir + fname,
    station_lon=station_lon,
    station_lat=station_lat,
    epsilon=epsilon
)

/home/paulinast/repos/github/machine-ocean-satdata/notebooks/../sar.py:164: RuntimeWarning: divide by zero encountered in log10
  s0 = 10.*np.log10(s0)


In [23]:
n = Nansat(data_dir + fname)
n

----------------------------------------
/lustre/storeB/project/IT/geout/machine-ocean/data_raw/sentinel/S1B_EW_GRDM_1SDH_20170720T084730_20170720T084830_006569_00B8D6_F92F.SAFE----------------------------------------
Mapper: sentinel1_l1Band : 1 DN_HH
  dataType: 2
  name: DN_HH
  SourceBand: 1
  SourceFilename: /lustre/storeB/project/IT/geout/machine-ocean/data_raw/sentinel/S1B_EW_GRDM_1SDH_20170720T084730_20170720T084830_006569_00B8D6_F92F.SAFE/measurement/s1b-ew-grd-hh-20170720t084730-20170720t084830-006569-00b8d6-001.tiff
Band : 2 DN_HV
  dataType: 2
  name: DN_HV
  SourceBand: 1
  SourceFilename: /lustre/storeB/project/IT/geout/machine-ocean/data_raw/sentinel/S1B_EW_GRDM_1SDH_20170720T084730_20170720T084830_006569_00B8D6_F92F.SAFE/measurement/s1b-ew-grd-hv-20170720t084730-20170720t084830-006569-00b8d6-002.tiff
Band : 3 sigmaNought_HH
  dataType: 7
  name: sigmaNought_HH
  SourceBand: 1
  SourceFilename: /vsimem/RNIFDTL75X.vrt
Band : 4 noise_HH
  dataType: 7
  name: noise_HH
  Sou

In [25]:
sar.crop_sar_data(n, station_lon, station_lat, epsilon)

(10555, 8332, 2, 3)

In [28]:
# Find band number of real valued HH or VV polarization NRCS
try:
    band_no = n.get_band_number({
        'standard_name': 'surface_backwards_scattering_coefficient_of_radar_wave',
        'polarization': 'HH',
        'dataType': '6',})
except ValueError:
    band_no = n.get_band_number({
        'standard_name': 'surface_backwards_scattering_coefficient_of_radar_wave',
        'polarization': 'VV',
        'dataType': '6',})
    
pol = n.get_metadata(key='polarization', band_id=band_no)

In [29]:
# Get NRCS, incidence angle, and sensor azimuth angle
s0 = n[band_no]
inc = n['incidence_angle']
az = n['look_direction']

In [30]:
s0

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)